# Generated by Django 5.2.9 on 2026-02-02 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(default='defaults/avatar.png', upload_to='avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('job_title', models.CharField(blank=True, help_text='Ex: CEO at Bird', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(blank=True, help_text='Separados por vírgula', max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('text', 'Bird (Texto)'), ('image', 'Photo (Insta)'), ('video', 'Clip (TikTok)'), ('story', 'Story (Snap)'), ('article', 'Article (Linkd)')], default='text', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('connections', 'Conexões'), ('close_friends', 'Melhores Amigos'), ('private', 'Apenas Eu')], default='public', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_birds', to=settings.AUTH_USER_MODEL)),
                ('original_bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebirds', to='core.bird')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.bird')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_birds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post_type', 'created_at'], name='core_bird_post_ty_c46b0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('muted', 'Silenciado')], default='active', max_length=20)),
                ('is_close_friend', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'target')},
            },
        ),
    ]
