# Generated by Django 5.2.9 on 2026-02-07 15:32

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='socialbond',
            name='custom_label',
        ),
        migrations.AddField(
            model_name='bird',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público'), ('friends', 'Amigos'), ('private', 'Privado')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_event_cover),
        ),
        migrations.AddField(
            model_name='evento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configurações de Privacidade'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='post_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('story', 'Story')], default='text', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf_document',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF/Documento'),
        ),
        migrations.AlterField(
            model_name='socialbond',
            name='type',
            field=models.CharField(choices=[('friend', 'Amigo'), ('bestie', 'Melhor Amigo'), ('dating', 'Namorando'), ('married', 'Casado(a)'), ('father', 'Pai'), ('mother', 'Mãe'), ('son', 'Filho(a)'), ('sibling', 'Irmão/Irmã'), ('colleague', 'Colega')], default='friend', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('community', 'user')},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.bird')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bird')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
