# Generated by Django 5.2.9 on 2026-02-08 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_connection_connection_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Membro Premium'),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Desde'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('like', 'Curtiu'), ('comment', 'Comentou'), ('follow', 'Seguiu'), ('bond', 'Laço Social'), ('system', 'Sistema'), ('moderation', 'Moderação')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AddIndex(
            model_name='socialbond',
            index=models.Index(fields=['requester', 'target'], name='core_social_request_6b5977_idx'),
        ),
        migrations.AddIndex(
            model_name='socialbond',
            index=models.Index(fields=['status'], name='core_social_status_40918b_idx'),
        ),
    ]
