# Generated by Django 5.2.11 on 2026-04-03 15:43

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_social_foundation_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('stream_type', models.CharField(choices=[('normal', 'Transmissão Normal'), ('pk', 'Batalha PK'), ('sala', 'Sala de Conversa (Múltiplos)')], default='normal', max_length=15)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='streams/covers/')),
                ('viewers_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='Geral', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('location', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameIndex(
            model_name='connection',
            new_name='core_connec_target__557842_idx',
            old_name='core_connec_target__d69c49_idx',
        ),
        migrations.RenameIndex(
            model_name='connection',
            new_name='core_connec_followe_8b5090_idx',
            old_name='core_connec_followe_e0d75d_idx',
        ),
        migrations.RenameIndex(
            model_name='savedpost',
            new_name='core_savedp_user_id_eebc46_idx',
            old_name='core_savedp_user_id_29f4f7_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_chat_attachment),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='gorjeio/group_icons/'),
        ),
        migrations.AddField(
            model_name='chatfolder',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='folders', to='core.room'),
        ),
        migrations.AddField(
            model_name='chatfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestream',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guested_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestream',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chatfolder',
            unique_together={('user', 'name')},
        ),
    ]
